version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "cd DVM-Recruitment-Task/ && gunicorn DVM_task3.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/azureuser/ecommerce3/staticfiles:Z
      - media_volume:/home/azureuser/ecommerce3/mediafiles:Z
      - log_volume:/home/azureuser/ecommerce3/logs
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgress_db}
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/DVM_task3:/etc/nginx/conf.d/default.conf
      - static_volume:/home/azureuser/ecommerce3/staticfiles/:Z
      - media_volume:/home/azureuser/ecommerce3/mediafiles/:Z
      - log_volume:/home/azureuser/ecommerce3/logs
      - /etc/letsencrypt/live/${domain}/privkey.pem:/etc/letsencrypt/live/${domain}/privkey.pem
      - /etc/letsencrypt/live/${domain}/fullchain.pem:/etc/letsencrypt/live/${domain}/fullchain.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
volumes:
   postgres_data:
   media_volume:
   static_volume:
   log_volume:
